### ISSUE TITLE
include React should be include react

### ISSUE THREAD

**Issue by braco** [t4t5/react-native-router#67]
ERROR in ./~/react-native-router/~/react-native/Libraries/react-native/react-native.js
Module build failed: SyntaxError: /private/var/www/ditto/node_modules/react-native-router/node_modules/react-native/Libraries/react-native/react-native.js: Line 20: Did you mean "react"?
  18 | //   var ReactNative = {...require('React'), /* additions */}
  19 | //
> 20 | var ReactNative = Object.assign(Object.create(require('React')), {

**Comment by niftylettuce** [comment]
same bug

```log
ERROR in ./~/react-native-router/~/react-native/Libraries/react-native/react-native.js
Module build failed: SyntaxError: /Users/nexus/Public/myproject/react-native/node_modules/react-native-router/node_modules/react-native/Libraries/react-native/react-native.js: Line 20: Did you mean "react"?
  18 | //   var ReactNative = {...require('React'), /* additions */}
  19 | //
> 20 | var ReactNative = Object.assign(Object.create(require('React')), {
     |                                                       ^
  21 |   // Components
  22 |   ActivityIndicatorIOS: require('ActivityIndicatorIOS'),
  23 |   DatePickerIOS: require('DatePickerIOS'),
    at File.errorWithNode (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/transformation/file/index.js:489:13)
    at check (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/transformation/transformers/validation/react.js:23:18)
    at NodePath.CallExpression (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/transformation/transformers/validation/react.js:40:7)
    at NodePath.call (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitMultiple (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitMultiple (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:107:26)
    at TraversalContext.visitSingle (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/Users/nexus/Public/myproject/react-native/node_modules/babel-core/lib/traversal/path/context.js:107:26)
```

**Comment by niftylettuce** [comment]
See <https://github.com/mjohnston/react-native-webpack-server/issues/50>

**Comment by sethx** [comment]
Please use: github.com/MikaelCarpenter/gb-native-router
