### ISSUE TITLE
Error running react-native run-android

### ISSUE THREAD

**Issue by kitolog** [t4t5/react-native-router#70]
Error building DepdendencyGraph:
 Error: Naming collision detected: /path/node_modules/react-native-router/node_modules/react-native/node_modules/react-tools/src/vendor/performance/performanceNow.js collides with  /path/node_modules/react-native/node_modules/react-tools/src/shared/vendor/performance/performanceNow.js
    at HasteMap._updateHasteMap ( /path/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:123:13)
    at /path/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:95:28
    at tryCallOne (/path/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /path/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/path/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
Process terminated. Press <enter> to close the window

**Comment by gucheen** [comment]
Same problem
```
 Error: Naming collision detected: /path/node_modules/react-native-router/node_modules/react-native/packager/package.json collides with /path/node_modules/react-native/packager/package.json
    at HasteMap._updateHasteMap (HasteMap.js:123:13)
    at HasteMap.js:104:32
    at tryCallOne (/path/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /path/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (path/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
~
```

Node: 4.2.3
NPM: 2.14.7

**Comment by sethx** [comment]
Please use github.com/MikaelCarpenter/gb-native-router

**Comment by radubrehar** [comment]
Same problem here @t4t5 react-native should be in peerDependencies. Do you accept prs?

**Comment by charpeni** [comment]
@radubrehar He will not accept pull request cause this repo is no longer maintained.

As @sethx mentioned it, if you want an updated fork please refer to http://github.com/MikaelCarpenter/gb-native-router.
