### ISSUE TITLE
Duplicate module name

### ISSUE THREAD

**Issue by victorpavlenko** [t4t5/react-native-router#78]
> Failed to build DependencyGraph: @providesModule naming collision:
>   Duplicate module name: ARTSerializablePath
>   Paths: C:\Users\pavle\AwesomeProject\node_modules\react-native-router\node_modules\react-native\Libraries\ART\ARTSerializablePath.js collides with C:\Users\pavle\AwesomeProject\node_modules\react-native\Libraries\ART\ARTSerializablePath.js
> 
> This error is caused by a @providesModule declaration with the same name accross two different files.
> Error: @providesModule naming collision:
>   Duplicate module name: ARTSerializablePath
>   Paths: C:\Users\pavle\AwesomeProject\node_modules\react-native-router\node_modules\react-native\Libraries\ART\ARTSerializablePath.js collides with C:\Users\pavle\AwesomeProject\node_modules\react-native\Libraries\ART\ARTSerializablePath.js
> 
> This error is caused by a @providesModule declaration with the same name accross two different files.
>     at HasteMap._updateHasteMap (C:\Users\pavle\AwesomeProject\node_modules\node-haste\lib\DependencyGraph\HasteMap.js:162:15)
>     at C:\Users\pavle\AwesomeProject\node_modules\node-haste\lib\DependencyGraph\HasteMap.js:127:25

**Comment by c4d3r** [comment]
Have the same error

**Comment by SeanAvery** [comment]
@Xurma2 I am also getting a duplicate (naming collision) on `react-native-router`'s react-native dependency. However, mine is throwing an error on the`Sample` library.

@c4d3r Has `react-native-route` moved to `react-native-simple-router-community`?

**Comment by SeanAvery** [comment]
@Xurma2 Moved over to react-native-simple-router. Appears to have the same functionality and does not throw naming collision :)
